import type {
  EventPackage,
  PackageAddon,
  Character,
  MenuItem,
  SiteSettings,
} from "./types";

export const packages: EventPackage[] = [
  {
    id: "experiencia-encantada",
    name: "Experiencia Encantada",
    slug: "experiencia-encantada",
    description: "El paquete base para crear momentos magicos. Incluye todo lo esencial para una fiesta infantil inolvidable.",
    price: 8500,
    duration: "5 horas",
    minGuests: 20,
    maxGuests: 50,
    includes: [
      "Salon de eventos por 5 horas",
      "Personal de servicio",
      "Invitaciones electronicas personalizadas",
      "Pastel decorado tematico",
      "Mesa de botanas variadas",
      "Bebidas ilimitadas (agua, jugo, refresco)",
      "Pintacaritas profesional",
      "Decoracion basica del salon",
      "Musica y sistema de sonido",
    ],
    isPremium: false,
  },
  {
    id: "experiencia-magica",
    name: "Experiencia Mágica",
    slug: "experiencia-magica",
    description: "La experiencia completa con personajes, entretenimiento y un servicio de primera para hacer realidad la fiesta de sus sueños.",
    price: 15500,
    duration: "6 horas",
    minGuests: 30,
    maxGuests: 80,
    includes: [
      "Todo lo incluido en Experiencia Encantada",
      "Salon de eventos por 6 horas",
      "Seleccion de personaje mascota",
      "Pinata tematica personalizada",
      "Regalo sorpresa para el festejado",
      "Barra de ensaladas y snacks",
      "Personal de servicio capacitado completo",
      "Decoracion tematica del salon",
      "Sesion de fotos con personaje",
      "Show de magia interactivo",
      "Area de juegos inflables",
    ],
    isPremium: true,
  },
];

export const addons: PackageAddon[] = [
  // Decoración
  { id: "flores", name: "Flores", category: "decoracion", description: "Arreglos florales para decorar el evento", price: 650 },
  { id: "centro-mesa", name: "Centro de Mesa", category: "decoracion", description: "Centros de mesa decorativos (desde)", price: 400 },
  { id: "arreglos-globos", name: "Arreglos con Globos", category: "decoracion", description: "Arreglos decorativos con globos (desde)", price: 1500 },
  { id: "telas", name: "Telas", category: "decoracion", description: "Decoración con telas para el salón", price: 15000, maxQuantity: 1 },
  { id: "photo-opportunity", name: "Photo Opportunity", category: "decoracion", description: "Escenografía para fotos temáticas", price: 10000, maxQuantity: 1 },
  // Comida
  { id: "pastel-fondant", name: "Pastel Fondant", category: "comida", description: "Pastel de fondant personalizado (desde)", price: 3000, maxQuantity: 1 },
  { id: "mesa-de-dulces", name: "Mesa de Dulces", category: "comida", description: "Mesa de dulces temática completa", price: 15000, maxQuantity: 1 },
  { id: "carrito-botanas", name: "Carrito de Botanas", category: "comida", description: "Carrito con variedad de botanas", price: 4500, maxQuantity: 1 },
  { id: "carrito-helados", name: "Carrito de Helados", category: "comida", description: "Carrito de helados para los invitados", price: 6500, maxQuantity: 1 },
  { id: "carrito-crepas", name: "Carrito de Crepas", category: "comida", description: "Carrito de crepas dulces y saladas", price: 5000, maxQuantity: 1 },
  { id: "carrito-hotcakes", name: "Carrito de Mini Hot Cakes", category: "comida", description: "Carrito de mini hot cakes con toppings", price: 4500, maxQuantity: 1 },
  { id: "barra-cafe", name: "Barra de Café", category: "comida", description: "Barra de café con bebidas variadas", price: 4500, maxQuantity: 1 },
  { id: "espiropapas", name: "Espiropapas", category: "comida", description: "Estación de espiropapas", price: 4500, maxQuantity: 1 },
  { id: "banderillas", name: "Banderillas", category: "comida", description: "Estación de banderillas", price: 4500, maxQuantity: 1 },
  { id: "esquites-elotes", name: "Esquites / Elotes", category: "comida", description: "Estación de esquites y elotes", price: 4500, maxQuantity: 1 },
  // Entretenimiento
  { id: "botargas", name: "Botargas", category: "entretenimiento", description: "Personajes botargas para el evento", price: 3800 },
  { id: "pinata", name: "Piñata sin Dulces", category: "entretenimiento", description: "Piñata temática (sin dulces incluidos)", price: 1300, maxQuantity: 1 },
  { id: "shows", name: "Shows", category: "entretenimiento", description: "Espectáculos en vivo para los niños (desde)", price: 6000 },
  { id: "dj", name: "DJ", category: "entretenimiento", description: "DJ profesional para ambientar la fiesta", price: 4500, maxQuantity: 1 },
  { id: "animadores", name: "Animadores", category: "entretenimiento", description: "Animadores profesionales para la fiesta", price: 1500 },
  { id: "experimentos", name: "Experimentos", category: "entretenimiento", description: "Show de experimentos divertidos para niños", price: 4500, maxQuantity: 1 },
  { id: "canon-espuma", name: "Cañón de Espuma", category: "entretenimiento", description: "Cañón de espuma para diversión al aire libre", price: 4500, maxQuantity: 1 },
  { id: "recuerditos", name: "Recuerditos", category: "entretenimiento", description: "Recuerdos para cada invitado (precio por pieza)", price: 200 },
  { id: "meseros", name: "Meseros", category: "entretenimiento", description: "Meseros adicionales para el evento (por persona)", price: 800 },
  // Manualidades (precio por niño)
  { id: "peluche-shop", name: "Peluche Shop", category: "manualidades", description: "Taller de peluches personalizado (precio por niño)", price: 300 },
  { id: "manos-cera", name: "Manos de Cera", category: "manualidades", description: "Actividad de manos de cera (precio por niño)", price: 270 },
  { id: "decorar-gorra", name: "Decorar tu Gorra", category: "manualidades", description: "Taller de decoración de gorras (precio por niño)", price: 150 },
  { id: "decorar-termo", name: "Decorar tu Termo", category: "manualidades", description: "Taller de decoración de termos (precio por niño)", price: 100 },
  { id: "decoracion-galletas", name: "Decoración de Galletas", category: "manualidades", description: "Taller de decoración de galletas (precio por niño)", price: 150 },
  { id: "lampara-lava", name: "Lámpara de Lava", category: "manualidades", description: "Taller de lámparas de lava (precio por niño)", price: 150 },
  { id: "cuadros-personalizados", name: "Cuadros Personalizados", category: "manualidades", description: "Taller de cuadros (precio por niño)", price: 140 },
  { id: "perfumes", name: "Perfumes", category: "manualidades", description: "Taller de perfumes (precio por niño)", price: 120 },
  { id: "jabones", name: "Jabones", category: "manualidades", description: "Taller de jabones (precio por niño)", price: 120 },
  { id: "slime", name: "Slime", category: "manualidades", description: "Taller de slime (precio por niño)", price: 90 },
  { id: "ceramica", name: "Cerámica", category: "manualidades", description: "Taller de cerámica (precio por niño)", price: 90 },
  { id: "chamarra-mezclilla", name: "Chamarra de Mezclilla", category: "manualidades", description: "Personaliza tu chamarra de mezclilla (precio por niño)", price: 1400 },
];

export const characters: Character[] = [
  { id: "caya", name: "Caya", description: "Un hada encantadora con alas brillantes y una varita de estrella dorada. Siempre lista para cumplir deseos y llenar de magia cada fiesta.", color: "fairy", gradient: "from-fairy-400 to-fairy-600", image: "/images/characters/caya.png" },
  { id: "maxi", name: "Maxi", description: "Un duende travieso y alegre con su gorro turquesa y una paleta magica. Le encanta hacer travesuras divertidas y sacar sonrisas.", color: "enchant", gradient: "from-enchant-400 to-enchant-600", image: "/images/characters/maxi.png" },
  { id: "migi", name: "Migi", description: "Un gatito blanco super inteligente con lentes azules y una capa de hechicero. Mezcla tecnologia y magia para crear aventuras increibles.", color: "cobalt", gradient: "from-cobalt-400 to-cobalt-600", image: "/images/characters/migi.png" },
  { id: "nene", name: "Nene", description: "Un dragoncito morado adorable con alas de arcoiris y una pancita dorada. Le encanta jugar con estrellas y repartir abrazos.", color: "lime", gradient: "from-lime-400 to-magic-400", image: "/images/characters/nene.png" },
  { id: "nalushka", name: "Nalushka", description: "La perrita mas tierna y esponjosa con su mono rosa brillante. Siempre esta lista para dar besitos y jugar con todos.", color: "orange", gradient: "from-orange-400 to-fairy-400", image: "/images/characters/nalushka.png" },
];

export const menuItems: MenuItem[] = [
  // Aguas
  { id: "agua-jamaica", name: "Jamaica", category: "aguas" },
  { id: "agua-horchata", name: "Horchata", category: "aguas" },
  { id: "agua-limon", name: "Limón", category: "aguas" },
  { id: "agua-limon-chia", name: "Limón con Chía", category: "aguas" },
  { id: "agua-pina-hierbabuena", name: "Piña con Hierbabuena", category: "aguas" },
  { id: "agua-sandia", name: "Sandía", category: "aguas" },
  { id: "agua-pepino-limon", name: "Pepino Limón", category: "aguas" },
  { id: "agua-naranja", name: "Naranja", category: "aguas" },
  // Guisados
  { id: "mole-rojo-pollo", name: "Mole Rojo con Pollo", category: "guisados" },
  { id: "mole-verde", name: "Mole Verde con Pollo o Puerco", category: "guisados" },
  { id: "chicharron-verde", name: "Chicharrón Verde", category: "guisados" },
  { id: "bisteck-pasilla-nopales", name: "Bisteck con Chile Pasilla y Nopales o con Chile Morita", category: "guisados" },
  { id: "milanesa", name: "Milanesa de Res o de Pollo", category: "guisados" },
  { id: "chiles-rellenos", name: "Chiles Rellenos de Queso", category: "guisados" },
  { id: "albondigas-res", name: "Albóndigas de Res", category: "guisados" },
  { id: "tortitas-pollo-morita", name: "Tortitas de Pollo en Chile Morita", category: "guisados" },
  { id: "zetas-pollo-verde", name: "Zetas con Pollo y Chile Verde", category: "guisados" },
  { id: "papas-chorizo", name: "Papas con Chorizo", category: "guisados" },
  { id: "papas-horno-guisado", name: "Papas al Horno", category: "guisados" },
  { id: "rajas-crema", name: "Rajas con Crema", category: "guisados" },
  { id: "cochinita-pibil", name: "Cochinita Pibil", category: "guisados" },
  { id: "tinga-pollo", name: "Tinga de Pollo", category: "guisados" },
  { id: "calabazas-mexicana", name: "Calabazas a la Mexicana", category: "guisados" },
  { id: "bisteck-mexicana", name: "Bisteck a la Mexicana", category: "guisados" },
  { id: "bisteck-morita", name: "Bisteck en Chile Morita", category: "guisados" },
  { id: "champinones-mexicana", name: "Champiñones a la Mexicana", category: "guisados" },
  { id: "costillas-bbq", name: "Costillas BBQ", category: "guisados" },
  { id: "costillas-chile", name: "Costillas en Chile", category: "guisados" },
  { id: "chicharron-prensado", name: "Chicharrón Prensado con Guajillo", category: "guisados" },
  // Guarniciones
  { id: "arroz", name: "Arroz", category: "guarniciones" },
  { id: "frijoles-charros", name: "Frijoles Charros", category: "guarniciones" },
  { id: "frijoles-refritos", name: "Frijoles Refritos", category: "guarniciones" },
  { id: "spaghetti-blanco", name: "Spaghetti Blanco", category: "guarniciones" },
  { id: "ensalada-fresca", name: "Ensalada Fresca", category: "guarniciones" },
  { id: "papas-horno-guarnicion", name: "Papas al Horno", category: "guarniciones" },
  { id: "pure-papa", name: "Puré de Papa", category: "guarniciones" },
  // Menú Niños — opciones principales (a escoger 2)
  { id: "ninos-pizza", name: "Pizza", category: "menu-ninos" },
  { id: "ninos-banderillas", name: "Banderillas", category: "menu-ninos" },
  { id: "ninos-hamburguesas", name: "Hamburguesas", category: "menu-ninos" },
  { id: "ninos-nuggets", name: "Nuggets", category: "menu-ninos" },
  { id: "ninos-rollitos-jamon", name: "Rollitos de Jamoncitos", category: "menu-ninos" },
  { id: "ninos-pasta-blanca", name: "Pasta Blanca", category: "menu-ninos" },
  // Menú Niños — acompañamientos (a escoger 1)
  { id: "ninos-papas-francesa", name: "Papas a la Francesa", category: "menu-ninos", description: "Acompañamiento" },
  { id: "ninos-verduras", name: "Verduras", category: "menu-ninos", description: "Acompañamiento" },
  // Snacks (escoge 18)
  { id: "snack-papas-naturales", name: "Papas Naturales", category: "snacks" },
  { id: "snack-papas-queso", name: "Papas Queso", category: "snacks" },
  { id: "snack-papas-adobadas", name: "Papas Adobadas", category: "snacks" },
  { id: "snack-papas-jalapeno", name: "Papas Jalapeño", category: "snacks" },
  { id: "snack-ruffles-queso", name: "Ruffles de Queso", category: "snacks" },
  { id: "snack-chips-fuego", name: "Chips Fuego", category: "snacks" },
  { id: "snack-chips-jalapeno", name: "Chips Jalapeño", category: "snacks" },
  { id: "snack-palomitas-naturales", name: "Palomitas Naturales", category: "snacks" },
  { id: "snack-palomitas-queso", name: "Palomitas Queso", category: "snacks" },
  { id: "snack-platanitos", name: "Platanitos", category: "snacks" },
  { id: "snack-doritos-queso", name: "Doritos Queso", category: "snacks" },
  { id: "snack-doritos-pizzerola", name: "Doritos Pizzerola", category: "snacks" },
  { id: "snack-takis-fuego", name: "Takis Fuego", category: "snacks" },
  { id: "snack-churritos-naturales", name: "Churritos Naturales", category: "snacks" },
  { id: "snack-churritos-chipotle", name: "Churritos Chipotle", category: "snacks" },
  { id: "snack-churritos-fuego", name: "Churritos Fuego", category: "snacks" },
  { id: "snack-churritos-limon-chile", name: "Churritos Limón & Chile", category: "snacks" },
  { id: "snack-cazares", name: "Cazares", category: "snacks" },
  { id: "snack-chicharrones-harina", name: "Chicharrones de Harina", category: "snacks" },
  { id: "snack-cheetos-queso", name: "Cheetos de Queso", category: "snacks" },
  { id: "snack-cheetos-fuego", name: "Cheetos Fuego", category: "snacks" },
  { id: "snack-cuertitos", name: "Cuertitos Preparados", category: "snacks" },
  { id: "snack-jicama", name: "Jícama Rayada", category: "snacks" },
  { id: "snack-zanahoria", name: "Zanahoria Rayada", category: "snacks" },
  { id: "snack-pepino", name: "Pepino Rayado", category: "snacks" },
  { id: "snack-mango", name: "Mango Picado", category: "snacks" },
  { id: "snack-pina", name: "Piña Picada", category: "snacks" },
  { id: "snack-sandia", name: "Sandía Picada", category: "snacks" },
  { id: "snack-cacahuate-japones", name: "Cacahuate Japonés", category: "snacks" },
  { id: "snack-cacahuate-habanero", name: "Cacahuate Habanero", category: "snacks" },
  { id: "snack-cacahuate-hotnuts", name: "Cacahuate Hot-Nuts", category: "snacks" },
  { id: "snack-cacahuate-chile-limon", name: "Cacahuate Chile Limón", category: "snacks" },
  { id: "snack-cacahuate-limon-sal", name: "Cacahuate Limón y Sal", category: "snacks" },
  { id: "snack-habas-chile", name: "Habas con Chile", category: "snacks" },
  { id: "snack-pepitas", name: "Pepitas sin Cáscara", category: "snacks" },
  { id: "snack-arandanos-chile", name: "Arándanos con Chile", category: "snacks" },
  { id: "snack-manguitos-chile", name: "Manguitos con Chile", category: "snacks" },
  { id: "snack-pinas-enchiladas", name: "Piñas Enchiladas", category: "snacks" },
  { id: "snack-gomitas-fruta-chile", name: "Gomitas de Fruta con Chile", category: "snacks" },
  { id: "snack-gomitas-frutas", name: "Gomitas de Frutas", category: "snacks" },
  { id: "snack-gomitas-panditas", name: "Gomitas Panditas", category: "snacks" },
  { id: "snack-gomitas-gusano", name: "Gomitas de Gusano", category: "snacks" },
  { id: "snack-gomitas-pinguino", name: "Gomitas de Pingüino", category: "snacks" },
  { id: "snack-gomitas-dientes", name: "Gomitas de Dientes", category: "snacks" },
  { id: "snack-gomitas-gotita", name: "Gomitas de Gotita", category: "snacks" },
  { id: "snack-pica-fresas", name: "Pica Fresas", category: "snacks" },
  { id: "snack-skwinkles", name: "Skwinkles", category: "snacks" },
  { id: "snack-pulparindos", name: "Pulparindos", category: "snacks" },
  { id: "snack-tamaroca", name: "Tamaroca", category: "snacks" },
  { id: "snack-bolitas-pelon", name: "Bolitas de Pelón", category: "snacks" },
  { id: "snack-bolitas-pulparindo", name: "Bolitas de Pulparindo", category: "snacks" },
];

export const siteSettings: SiteSettings = {
  name: "Habia una vez",
  tagline: "Salon de Eventos Infantiles",
  subtitle: "by Pamela Hermo Eventos",
  phone: "55 19 95 70 04",
  whatsapp: "5219957004",
  email: "contacto@habiaunavez.com",
  address: "Cda. de Gruta 19, Jardines del Pedregal, 01900 Álvaro Obregón, Ciudad de México, CDMX",
  instagram: "https://instagram.com/habiaunavezbypamhermo",
  facebook: "https://facebook.com/habiaunavez",
  mapUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3764.5!2d-99.2!3d19.3!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMTnCsDE4JzAwLjAiTiA5OcKwMTInMDAuMCJX!5e0!3m2!1ses-419!2smx!4v1",
};
