import type {
  EventPackage,
  PackageAddon,
  Character,
  MenuItem,
  SiteSettings,
} from "./types";

export const packages: EventPackage[] = [
  {
    id: "experiencia-encantada",
    name: "Experiencia Encantada",
    slug: "experiencia-encantada",
    description: "El paquete base para crear momentos magicos. Incluye todo lo esencial para una fiesta infantil inolvidable.",
    price: 8500,
    duration: "5 horas",
    minGuests: 20,
    maxGuests: 50,
    includes: [
      "Salon de eventos por 5 horas",
      "Personal de servicio",
      "Invitaciones electronicas personalizadas",
      "Pastel decorado tematico",
      "Mesa de botanas variadas",
      "Bebidas ilimitadas (agua, jugo, refresco)",
      "Pintacaritas profesional",
      "Decoracion basica del salon",
      "Musica y sistema de sonido",
    ],
    isPremium: false,
  },
  {
    id: "premium",
    name: "Premium",
    slug: "premium",
    description: "La experiencia completa con personajes, entretenimiento premium y un servicio de primera para los mas exigentes.",
    price: 15500,
    duration: "6 horas",
    minGuests: 30,
    maxGuests: 80,
    includes: [
      "Todo lo incluido en Experiencia Encantada",
      "Salon de eventos por 6 horas",
      "Seleccion de personaje mascota",
      "Pinata tematica personalizada",
      "Regalo sorpresa para el festejado",
      "Barra de ensaladas y snacks premium",
      "Personal de servicio capacitado completo",
      "Decoracion tematica premium del salon",
      "Sesion de fotos con personaje",
      "Show de magia interactivo",
      "Area de juegos inflables",
    ],
    isPremium: true,
  },
];

export const addons: PackageAddon[] = [
  { id: "personaje-extra", name: "Personaje adicional", category: "personajes", description: "Un personaje mascota adicional para acompanar la fiesta", price: 2500 },
  { id: "show-magia", name: "Show de magia", category: "personajes", description: "Espectaculo de magia interactivo de 30 minutos", price: 3000 },
  { id: "mesa-dulces", name: "Mesa de dulces", category: "comida", description: "Mesa de dulces tematica con variedad de golosinas", price: 3500, maxQuantity: 1 },
  { id: "fuente-chocolate", name: "Fuente de chocolate", category: "comida", description: "Fuente de chocolate con frutas y malvaviscos", price: 2000, maxQuantity: 1 },
  { id: "pizza-extra", name: "Paquete de pizzas (20 pzs)", category: "comida", description: "20 porciones de pizza variada", price: 1200, maxQuantity: 5 },
  { id: "hot-dogs", name: "Hot dogs (30 pzs)", category: "comida", description: "30 hot dogs preparados", price: 900, maxQuantity: 5 },
  { id: "arco-globos", name: "Arco de globos tematico", category: "decoracion", description: "Arco decorativo de globos con colores personalizados", price: 1800, maxQuantity: 2 },
  { id: "centro-mesa", name: "Centros de mesa (10 pzs)", category: "decoracion", description: "Set de 10 centros de mesa tematicos", price: 1500, maxQuantity: 3 },
  { id: "letrero-nombre", name: "Letrero personalizado con nombre", category: "decoracion", description: "Letrero luminoso con el nombre del festejado", price: 800, maxQuantity: 1 },
  { id: "inflable-extra", name: "Inflable adicional", category: "entretenimiento", description: "Juego inflable extra para la fiesta", price: 2500, maxQuantity: 2 },
  { id: "karaoke", name: "Karaoke infantil", category: "entretenimiento", description: "Sistema de karaoke con pantalla y canciones infantiles", price: 1500, maxQuantity: 1 },
  { id: "fotocabina", name: "Fotocabina con props", category: "entretenimiento", description: "Cabina de fotos con accesorios tematicos e impresion instantanea", price: 3500, maxQuantity: 1 },
];

export const characters: Character[] = [
  { id: "caya", name: "Caya", description: "Un hada encantadora con alas brillantes y una varita de estrella dorada. Siempre lista para cumplir deseos y llenar de magia cada fiesta.", color: "fairy", gradient: "from-fairy-400 to-fairy-600", image: "/images/characters/caya.png" },
  { id: "maxi", name: "Maxi", description: "Un duende travieso y alegre con su gorro turquesa y una paleta magica. Le encanta hacer travesuras divertidas y sacar sonrisas.", color: "enchant", gradient: "from-enchant-400 to-enchant-600", image: "/images/characters/maxi.png" },
  { id: "migi", name: "Migi", description: "Un gatito blanco super inteligente con lentes azules y una capa de hechicero. Mezcla tecnologia y magia para crear aventuras increibles.", color: "cobalt", gradient: "from-cobalt-400 to-cobalt-600", image: "/images/characters/migi.png" },
  { id: "nene", name: "Nene", description: "Un dragoncito morado adorable con alas de arcoiris y una pancita dorada. Le encanta jugar con estrellas y repartir abrazos.", color: "lime", gradient: "from-lime-400 to-magic-400", image: "/images/characters/nene.png" },
  { id: "nalushka", name: "Nalushka", description: "La perrita mas tierna y esponjosa con su mono rosa brillante. Siempre esta lista para dar besitos y jugar con todos.", color: "orange", gradient: "from-orange-400 to-fairy-400", image: "/images/characters/nalushka.png" },
];

export const menuItems: MenuItem[] = [
  { id: "agua-fresca", name: "Aguas frescas variadas", category: "bebidas" },
  { id: "jugos", name: "Jugos naturales", category: "bebidas" },
  { id: "refrescos", name: "Refrescos", category: "bebidas" },
  { id: "cafe", name: "Cafe y te", category: "bebidas" },
  { id: "mini-sandwiches", name: "Mini sandwiches", category: "botanas" },
  { id: "dedos-queso", name: "Dedos de queso", category: "botanas" },
  { id: "papas-gajos", name: "Papas en gajos", category: "botanas" },
  { id: "nachos", name: "Nachos con queso", category: "botanas" },
  { id: "coctel-frutas", name: "Coctel de frutas", category: "botanas" },
  { id: "pastel-fondant", name: "Pastel de fondant personalizado", category: "panaderia" },
  { id: "cupcakes", name: "Cupcakes decorados (24 pzs)", category: "panaderia" },
  { id: "cake-pops", name: "Cake pops (20 pzs)", category: "panaderia" },
  { id: "galletas-decoradas", name: "Galletas decoradas (30 pzs)", category: "panaderia" },
  { id: "nuggets", name: "Nuggets de pollo", category: "pollo" },
  { id: "alitas", name: "Alitas BBQ", category: "pollo" },
  { id: "pollo-empanizado", name: "Pollo empanizado", category: "pollo" },
  { id: "mini-hamburguesas", name: "Mini hamburguesas", category: "res" },
  { id: "albondigas", name: "Albondigas en salsa", category: "res" },
  { id: "salchichas", name: "Salchichas envueltas", category: "cerdo" },
  { id: "mini-hot-dogs", name: "Mini hot dogs", category: "cerdo" },
  { id: "tacos-pastor", name: "Tacos al pastor", category: "tacos" },
  { id: "tacos-bistec", name: "Tacos de bistec", category: "tacos" },
  { id: "tacos-pollo", name: "Tacos de pollo", category: "tacos" },
  { id: "mac-cheese", name: "Mac & Cheese", category: "infantil" },
  { id: "mini-pizzas", name: "Mini pizzas", category: "infantil" },
  { id: "quesadillas", name: "Quesadillas", category: "infantil" },
  { id: "espagueti", name: "Espagueti", category: "infantil" },
];

export const siteSettings: SiteSettings = {
  name: "Habia una vez",
  tagline: "Salon de Eventos Infantiles",
  subtitle: "by Pamela Hermo Eventos",
  phone: "55 19 95 70 04",
  whatsapp: "5219957004",
  email: "contacto@habiaunavez.com",
  address: "Cda. de Gruta 19, Jardines del Pedregal, Coyoacan, 01900 Ciudad de Mexico, CDMX",
  instagram: "https://instagram.com/habiaunavez",
  facebook: "https://facebook.com/habiaunavez",
  mapUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3764.5!2d-99.2!3d19.3!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMTnCsDE4JzAwLjAiTiA5OcKwMTInMDAuMCJX!5e0!3m2!1ses-419!2smx!4v1",
};
